const QUESTIONNAIRE_CRITERIA_MAP = {"learningFit":[1,2,3,4,5,6,36,37,38],"languageAcademic":[7,8,9,10,11,12,13],"commuteSleep":[],"homePhilosophy":[6,33,34,35,36,37,38],"individualSupport":[3,4,5,13,14,15,16,17],"interests":[39,40,41,42],"longTerm":[47,48,49],"bullyingViolence":[18,19,20,21,22,23,24,25,26,27,28,29],"security":[30,31,32],"trackRecord":[46,50]};

const TOMTOM_REFERENCE = {
  generated:'25 ส.ค. 2569',
  provider:'TomTom Routing API',
  model:'Historical Traffic Model',
  homeCoordinate:'13.7919909, 100.4373283',
  method:'20 model samples/route (Mon–Fri × 4 สัปดาห์ตัวอย่าง) using historicTrafficTravelTimeInSeconds; historical-pattern estimate, not archived actual trips'
};

DECISION_META.updated='25 ส.ค. 2569';
DECISION_META.note='ขาไปออกจากบ้าน 06:15 เหมือนกันทั้งสองโรงเรียน • ขากลับใช้เวลาเลิกเรียนจริง: เพลินพัฒนา 15:30 และอำนวยศิลป์ 14:30 • เวลาเดินทางอ้างอิง TomTom Historical Traffic Model (generated 25 ส.ค. 2569)';

const _p=SCHOOLS.find(s=>s.id==='plearnpattana');
Object.assign(_p.commute,{morningRange:[10,15],returnRange:[8,12],morningMedian:11.57,morningP90:11.65,returnMedian:8.35,returnP90:8.50,routeContext:'TomTom Historical Traffic Model: บ้าน → เพลินพัฒนา 06:15; เพลินพัฒนา → บ้าน 15:30',caveat:'TomTom model • Median/P90 จาก output 25 ส.ค. 2569 • ไม่ใช่ actual archived trips'});
const _a=SCHOOLS.find(s=>s.id==='amnuaysilpa');
Object.assign(_a.commute,{morningRange:[25,30],returnRange:[25,30],morningMedian:25.65,morningP90:25.97,morningNoTollMedian:25.65,morningNoTollP90:26.38,returnMedian:25.00,returnP90:25.42,routeContext:'TomTom Historical Traffic Model: บ้าน → อำนวยศิลป์ 06:15 (fastest; no-toll model ใกล้เคียงกัน); อำนวยศิลป์ → บ้าน 14:30',caveat:'TomTom model • Median/P90 จาก output 25 ส.ค. 2569 • ไม่ใช่ actual archived trips'});

(function(){
function loadMammoth(){if(window.mammoth)return Promise.resolve();return new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js';s.onload=ok;s.onerror=()=>no(new Error('โหลด DOCX parser ไม่สำเร็จ'));document.head.appendChild(s);});}
function nt(s){return String(s||'').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').replace(/\r/g,'').trim();}
function parseAnswers(text){
  const src=String(text||'').replace(/\r/g,''),re=/(?:^|\n)\s*(\d{1,2})\.\s*/g,marks=[];let m;
  while((m=re.exec(src)))marks.push({n:+m[1],start:m.index+(m[0][0]==='\n'?1:0),body:re.lastIndex});
  const out={};
  marks.forEach((x,i)=>{if(x.n<1||x.n>50)return;let b=src.slice(x.body,i+1<marks.length?marks[i+1].start:src.length).trim();const mk=b.match(/(?:คำตอบ|Answer)\s*[:：]\s*/i);if(mk)b=b.slice(mk.index+mk[0].length);else{const lines=b.split(/\n+/).map(nt).filter(Boolean);b=lines.length>1?lines.slice(1).join(' '):'';}out[x.n]=nt(b);});
  return out;
}
function quality(n,a){
  a=nt(a);if(a.length<8)return 0;let q=1;if(a.length>=45)q++;if(/(\d|%|เปอร์เซ็นต์|นาที|ชั่วโมง|วัน|ครั้ง|คน|ต่อห้อง|อัตราส่วน)/i.test(a))q++;if(/(ขั้นตอน|protocol|policy|นโยบาย|บันทึก|ติดตาม|intervention|ประเมิน|แจ้ง|review|pathway|support|CCTV|counsellor|psychologist|learning support|escalation|safeguard)/i.test(a))q++;if(/(ตัวอย่าง|เช่น|สถิติ|ข้อมูลย้อนหลัง|รายงาน|case|evidence|accredit|ผลลัพธ์)/i.test(a))q++;if(/(ไม่มีข้อมูล|ไม่ทราบ|ไม่สะดวกเปิดเผย|ไม่มีระบบ|ไม่มีนโยบาย|ไม่ได้บันทึก|ไม่สามารถให้ข้อมูล)/i.test(a))q=Math.min(q,2);if(n===28&&/ไม่เคย/.test(a))q=Math.max(q,4);return Math.min(5,q);
}
function autoCriterion(key,answers){
  const qs=QUESTIONNAIRE_CRITERIA_MAP[key]||[];if(!qs.length)return null;const vals=qs.map(n=>quality(n,answers[n]||'')),answered=vals.filter(Boolean);if(!answered.length)return null;const coverage=answered.length/qs.length,avg=answered.reduce((a,b)=>a+b,0)/answered.length;let v=1+4*(.55*coverage+.45*((avg-1)/4));const all=qs.map(n=>answers[n]||'').join(' ');if(/(ไม่มีข้อมูล|ไม่สะดวกเปิดเผย|ไม่มีระบบ|ไม่มีนโยบาย|ไม่ได้บันทึก|ไม่สามารถให้ข้อมูล)/i.test(all))v-=.5;return {score:Math.max(1,Math.min(5,Math.round(v))),reason:`ตอบ ${answered.length}/${qs.length} ข้อ • evidence quality ${avg.toFixed(1)}/5 • Q${qs.join(', Q')}`};
}
function commuteAuto(id){const s=SCHOOLS.find(x=>x.id===id),d=s.commute.morningMedian+s.commute.returnMedian;return {score:d<=25?5:d<=35?4:d<=45?3:d<=60?2:1,reason:`TomTom model median ไป-กลับ ${d.toFixed(2)} นาที/วัน`};}
function eh(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

window.addEventListener('DOMContentLoaded',()=>{
  state.scoreSources||={};state.autoDetails||={};state.questionnaires||={};
  const css=document.createElement('style');css.textContent='.upload-grid{display:grid;grid-template-columns:1fr;gap:12px;margin:14px 0}@media(min-width:760px){.upload-grid{grid-template-columns:1fr 1fr}}.upload-card{border:1px solid var(--line);border-radius:14px;padding:14px;background:#fbfcfe}.upload-card input{width:100%;margin:10px 0}.upload-status{font-size:13px;color:var(--muted)}.upload-status.ok{color:var(--green)}.upload-status.err{color:var(--red)}.auto-badge,.manual-badge{display:inline-block;margin-top:5px;padding:3px 7px;border-radius:999px;font-size:11px;font-weight:800}.auto-badge{background:var(--green-soft);color:#11684b}.manual-badge{background:var(--blue-soft);color:var(--blue)}.score-source{font-size:11px;color:var(--muted);margin-top:4px}.model-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.model-pill{font-size:12px;background:#f1f4f9;border:1px solid var(--line);border-radius:999px;padding:4px 8px}.q-details{margin-top:8px;font-size:12px;color:var(--muted)}';document.head.appendChild(css);

  const cc=document.querySelector('#commuteCards');if(cc){cc.innerHTML=SCHOOLS.map(s=>{const [m0,m1]=s.commute.morningRange,[r0,r1]=s.commute.returnRange,ntoll=s.id==='amnuaysilpa'?`<span class="model-pill">No-toll median ${s.commute.morningNoTollMedian.toFixed(2)} • P90 ${s.commute.morningNoTollP90.toFixed(2)}</span>`:'';return `<div class="metric"><div class="soft">${eh(s.shortName)}</div><b>เช้า • ออก ${s.commute.morningDeparture}</b><div class="big">${m0}–${m1} นาที</div><div>Arrival: <b>${addMin(s.commute.morningDeparture,m0)}–${addMin(s.commute.morningDeparture,m1)}</b></div><div class="model-row"><span class="model-pill">Median ${s.commute.morningMedian.toFixed(2)}</span><span class="model-pill">P90 ${s.commute.morningP90.toFixed(2)}</span>${ntoll}</div><div class="route-note">${eh(s.commute.routeContext)}</div><hr style="border:0;border-top:1px solid var(--line);margin:15px 0"><b>ขากลับ • ออก ${s.commute.returnDeparture}</b><div class="big">${r0}–${r1} นาที</div><div>Arrival: <b>${addMin(s.commute.returnDeparture,r0)}–${addMin(s.commute.returnDeparture,r1)}</b></div><div class="model-row"><span class="model-pill">Median ${s.commute.returnMedian.toFixed(2)}</span><span class="model-pill">P90 ${s.commute.returnP90.toFixed(2)}</span></div><div class="caveat">${eh(s.commute.caveat)}</div></div>`;}).join('');cc.insertAdjacentHTML('afterend',`<div class="caveat"><b>Reference:</b> ${eh(TOMTOM_REFERENCE.provider)} — ${eh(TOMTOM_REFERENCE.model)}, generated ${eh(TOMTOM_REFERENCE.generated)} • Home ${eh(TOMTOM_REFERENCE.homeCoordinate)} • ${eh(TOMTOM_REFERENCE.method)}</div>`);}
  const footer=document.querySelector('.footer');if(footer)footer.innerHTML='Commute source: <b>TomTom Routing API Historical Traffic Model</b> output generated 25 ส.ค. 2569. เป็น historical-pattern model estimate ไม่ใช่ actual archived trip history.';

  const score=document.querySelector('.score'),table=score?.querySelector('table');if(table)table.insertAdjacentHTML('beforebegin',`<div class="upload-grid"><div class="upload-card"><b>เพลินพัฒนา</b><div>Upload questionnaire ที่ตอบแล้ว (.docx/.txt)</div><input id="qfile-plearnpattana" type="file" accept=".docx,.txt"><div id="qstatus-plearnpattana" class="upload-status"></div><details class="q-details"><summary>ผลประมวลคะแนน</summary><div id="qdetails-plearnpattana"></div></details></div><div class="upload-card"><b>อำนวยศิลป์</b><div>Upload questionnaire ที่ตอบแล้ว (.docx/.txt)</div><input id="qfile-amnuaysilpa" type="file" accept=".docx,.txt"><div id="qstatus-amnuaysilpa" class="upload-status"></div><details class="q-details"><summary>ผลประมวลคะแนน</summary><div id="qdetails-amnuaysilpa"></div></details></div></div><div class="route-note"><b>Auto-score:</b> deterministic evidence rubric (ไม่ใช่ AI) จากความครบถ้วน ตัวเลข/เวลา ขั้นตอน/นโยบาย และหลักฐานในคำตอบ; manual override ได้ทุกช่อง และระบบไม่ได้ตรวจสอบความจริงของคำตอบโรงเรียน</div>`);

  function setAuto(id,answers){state.scores[id]||={};state.scoreSources[id]||={};state.autoDetails[id]||={};DECISION_CRITERIA.forEach(c=>{const r=c.key==='commuteSleep'?commuteAuto(id):autoCriterion(c.key,answers);if(r){state.scores[id][c.key]=r.score;state.scoreSources[id][c.key]='auto';state.autoDetails[id][c.key]=r;}});}
  function commute(){SCHOOLS.forEach(s=>{state.scores[s.id]||={};state.scoreSources[s.id]||={};state.autoDetails[s.id]||={};if(state.scoreSources[s.id].commuteSleep!=='manual'){const r=commuteAuto(s.id);state.scores[s.id].commuteSleep=r.score;state.scoreSources[s.id].commuteSleep='auto';state.autoDetails[s.id].commuteSleep=r;}});}
  function decorate(){document.querySelectorAll('[data-score]').forEach(sel=>{const id=sel.dataset.score,k=sel.dataset.key,td=sel.closest('td');td.querySelectorAll('.auto-badge,.manual-badge,.score-source').forEach(x=>x.remove());const src=state.scoreSources?.[id]?.[k],d=state.autoDetails?.[id]?.[k]?.reason||'';if(src)sel.insertAdjacentHTML('afterend',`<div class="${src==='auto'?'auto-badge':'manual-badge'}">${src.toUpperCase()}</div><div class="score-source">${eh(d)}</div>`);});document.querySelectorAll('#scoreBody tr').forEach((tr,i)=>{const c=DECISION_CRITERIA[i],q=QUESTIONNAIRE_CRITERIA_MAP[c.key]||[],cell=tr.children[2];if(!cell.querySelector('.qmap'))cell.insertAdjacentHTML('beforeend',`<div class="score-source qmap">${q.length?'Questionnaire: Q'+q.join(', Q'):'Source: TomTom commute model'}</div>`);});}
  function status(id){const s=document.querySelector('#qstatus-'+id),d=document.querySelector('#qdetails-'+id),q=state.questionnaires?.[id];if(!q){s.textContent='ยังไม่ได้อัปโหลด questionnaire';d.innerHTML='';return;}s.className='upload-status ok';s.textContent=`อ่านแล้ว: ${q.fileName} • พบคำตอบ ${q.count}/50 ข้อ`;d.innerHTML=DECISION_CRITERIA.map(c=>{const x=state.autoDetails?.[id]?.[c.key];return `<div><b>${eh(c.label)}</b>: ${x?.score??'—'}/5 — ${eh(x?.reason||'')}</div>`;}).join('');}
  async function upload(file,id){const s=document.querySelector('#qstatus-'+id);s.textContent='กำลังอ่าน…';try{let text;if(file.name.toLowerCase().endsWith('.docx')){await loadMammoth();text=(await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()})).value;}else text=await file.text();const answers=parseAnswers(text),count=Object.values(answers).filter(x=>nt(x).length>=8).length;if(!count)throw new Error('ไม่พบคำตอบ กรุณาตอบใต้แต่ละคำถาม หรือใส่ “คำตอบ:”');state.questionnaires[id]={fileName:file.name,count,answers};setAuto(id,answers);save();renderScoreRows();updateTotals();decorate();status(id);}catch(e){s.className='upload-status err';s.textContent='อ่านไฟล์ไม่สำเร็จ: '+e.message;}}
  commute();save();renderScoreRows();updateTotals();decorate();
  ['plearnpattana','amnuaysilpa'].forEach(id=>{status(id);document.querySelector('#qfile-'+id)?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)upload(f,id);});});
  score?.addEventListener('change',e=>{const x=e.target.closest?.('[data-score]');if(!x)return;state.scoreSources[x.dataset.score]||={};state.scoreSources[x.dataset.score][x.dataset.key]=x.value?'manual':'';save();decorate();},true);
  document.querySelector('#resetScores')?.addEventListener('click',()=>setTimeout(()=>{state.scoreSources={};state.autoDetails={};state.questionnaires={};commute();save();renderScoreRows();updateTotals();decorate();['plearnpattana','amnuaysilpa'].forEach(status);},0));
});
})();
